# ===============================
# Server
# ===============================
server.port=8080

# ===============================
# PostgreSQL Configuration
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/shortify
spring.datasource.username=shortify
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# Redis Configuration
# ===============================
spring.redis.host=localhost
spring.redis.port=6379

# ===============================
# Logging
# ===============================
logging.level.org.springframework=INFO
logging.level.com.shortify=DEBUG
