# ===============================
# Server
# ===============================
server.port=8080

# ===============================
# PostgreSQL Configuration
# ===============================
spring.datasource.url=jdbc:postgresql://postgres:5432/shortify
spring.datasource.username=shortify
spring.datasource.password=shortify

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# Redis Configuration
# ===============================
spring.redis.host=redis
spring.redis.port=6379

# ===============================
# Kafka Configuration
# ===============================
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.acks=1
spring.kafka.producer.retries=3
spring.kafka.producer.properties.linger.ms=10
spring.kafka.producer.properties.batch.size=16384
spring.kafka.producer.properties.compression.type=snappy

spring.kafka.consumer.bootstrap-servers=kafka:9092
spring.kafka.consumer.group-id=shortify-analytics-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=true
spring.kafka.consumer.properties.session.timeout.ms=30000
spring.kafka.consumer.properties.heartbeat.interval.ms=10000
spring.kafka.consumer.properties.max.poll.interval.ms=300000

spring.kafka.listener.type=batch
spring.kafka.listener.concurrency=3

# ===============================
# Logging
# ===============================
logging.level.org.springframework=INFO
logging.level.com.shortify=DEBUG
