name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # ---------------- BACKEND ----------------
      - name: Build Backend Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:latest ./shortify-backend

      - name: Push Backend Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest

      # ---------------- FRONTEND ----------------
      - name: Build Frontend Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest ./shortify-frontend

      - name: Push Frontend Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest